### ISSUE TITLE
Duplicate install instructions

### ISSUE THREAD

**Issue by abachma2** [cyclus/cyclus.github.com#361]
Looking at `source/user/install.rst`, there are multiple links for each type of install. There is a list of the install types, with some recommendations, and there is a `toctree` with the file names. So this creates a duplicate of the list. Some paths on how to remedy this:
- Leave the `:doc:` elements with the recommendations in `install.rst`, and remove the doc tree
- Remove the `:doc:` elements, leaving the `toctree` in `install.rst`. This would likely involve moving the recommendations into each of the files to keep that information present for users.

**Comment by bennibbelink** [comment]
I personally think that it is helpful to have the recommendations, so I'm partial to the first bullet above.  It would also require that we add a `:doc:` element for the Docker Install option.   

Could we possibly remove the references to "Custom" and "CMake" Cyclus Installations from `install.rst` since they are only relevant to installing from source? Both the "via Tarball" and "via Repository" pages reference the custom build options already.

**Comment by abachma2** [comment]
That's another thing I modify for this.

**Comment by abachma2** [comment]
I believe this was addressed in #362, so I'm closing it.
